require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe StepsController, type: :controller do

  let(:user) {FactoryBot.create(:user)}
  let(:recipe) {FactoryBot.create(:recipe, user: user)}

  # This should return the minimal set of attributes required to create a valid
  # Step. As you add validations to Step, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.attributes_for(:step)
  }

  let(:invalid_attributes) {
    {sequence_number: 2}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StepsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "POST #create" do
    context "with valid params" do
      let(:valid_params) {
        valid_attributes.merge({recipe_id: recipe.id})
      }
      it "creates a new Step" do
        expect {
          post :create, params: {step: valid_params}, session: valid_session
        }.to change(Step, :count).by(1)
      end

      it "renders a JSON response with the new step" do
        post :create, params: {step: valid_params}, session: valid_session
        expect(response).to have_http_status(:created),response.body
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(step_url(Step.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new step" do
        post :create, params: {step: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  context "with step created" do

    let(:step) {
      Step.create! valid_attributes.merge({recipe_id: recipe.id})
    }

    describe "GET #index" do
      it "returns a success response" do
        get :index, params: {}, session: valid_session
        expect(response).to be_success
      end
    end

    describe "GET #show" do
      it "returns a success response" do
        get :show, params: {id: step.to_param}, session: valid_session
        expect(response).to be_success
      end
    end

    describe "PUT #update" do
      context "with valid params" do
        let(:new_attributes) {
          {description: "new description"}
        }

        before do
          put :update, params: {id: step.to_param, step: new_attributes}, session: valid_session
        end
        it "updates the requested step" do
          step.reload
          expect(step.description).to eq("new description")
        end

        it "renders a JSON response with the step" do
          expect(response).to have_http_status(:ok)
          expect(response.content_type).to eq('application/json')
        end
      end

      context "with invalid params" do
        let(:invalid_attributes) {
          {description: nil}
        }
        it "renders a JSON response with errors for the step" do
          put :update, params: {id: step.to_param, step: invalid_attributes}, session: valid_session
          expect(response).to have_http_status(:unprocessable_entity)
          expect(response.content_type).to eq('application/json')
        end
      end
    end

    describe "DELETE #destroy" do
      it "destroys the requested step" do
        step                            # hydrate the step
        expect {
          delete :destroy, params: {id: step.to_param}, session: valid_session
        }.to change(Step, :count).by(-1)
      end
    end
  end
end
